model:
  name: "bert-base-uncased"
  num_labels: 4  # nutrient, quantity, food, unit

data:
  train_dir: "data/train"
  test_dir: "data/test"
  val_dir: "data/val"
  max_length: 128

training:
  batch_size: 32
  epochs: 5
  learning_rate: 2e-5
  warmup_steps: 500

inference:
  batch_size: 64
